package ast;

public enum NodeTypes {
	OPERATION, FUNCTION_DECLARATION, VARIABLE, VARIABLE_DECLARATION,RETURN_STATEMENT,CONSTANT, IF_STATEMENT, WHILE_STATEMENT, FUNCTION_CALL, PRINT_STATEMENT, CHANGE_TO_STATEMENT;
}
