package lexer;

public enum TokenTypes {
	FUNC_KEYWORD, VAR_KEYWORD, PRINT_KEYWORD, INTEGER_KEYWORD, FLOAT_KEYWORD, STRING_KEYWORD, BOOLEAN_KEYWORD, INTEGER_LITERAL, FLOAT_LITERAL, STRING_LITERAL, BOOLEAN_LITERAL, SEMICOLON, COMMA, BRACKET, OPERATOR, IDENTIFIER, RETURN_KEYWORD;

}
