package lexer;

public enum TokenTypes {
	BOOLEAN_KEYWORD, BOOLEAN_LITERAL, BRACKET, COMMA, ELSE_KEYWORD, END_KEYWORD, FLOAT_KEYWORD, FLOAT_LITERAL, FUNC_KEYWORD, IDENTIFIER, IF_KEYWORD, IMPORT_KEYWORD, INTEGER_KEYWORD, INTEGER_LITERAL, OPERATOR, PRINT_KEYWORD, RETURN_KEYWORD, SEMICOLON, STRING_KEYWORD, STRING_LITERAL, VAR_KEYWORD, VOID_KEYWORD, WHILE_KEYWORD, DOT, DYNAMIC_KEYWORD, STATIC_KEYWORD, CHANGE_KEYWORD, TO_KEYWORD;

}
