import stdlib.casts.stringToInt;
import stdlib.io.input;
import math.fibonacci;
func int printr int toPrint;
	println toPrint;
	return toPrint;
end;
func int factorial int n;
	if n 1 ==;
		return printr(1);
	end;
	return printr(n factorial(n 1 -) *);
end;

func int fastFactorial int n;
	var static int result 1 =;
	var static int i 1 =;
	while i n <=;
		result i *=;  
		println result;
		i 1 +=;
	end;
	return result;
end;
print "Podaj numer liczby w ci�gu fibonacciego z kt�rej b�dzie obliczona silnia: ";
fastFactorial(fib(stringToInt(input())));
